import React from "react";
import { Inter } from 'next/font/google'
import '@/styles/globals.css'
import {Links} from "@/components/links";
import StyledComponentsRegistry from "@/lib/registry";
import ScrollBar from "@/components/ScrollBar";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App Upd',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={{overflow: "hidden"}}>
      <ScrollBar/>
      <Links/>
      <h1>Layout</h1>
      <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  )
}


